<!-- Joyride code
<br> 
<ol class='hidden' id="chooseID">
  <li data-id="step1" data-button="Let's Start!">What's this?! &nbsp;</li>
  <li data-id="step2" data-button="Go on">Whats next? &nbsp;</li>
  <li data-id="step3" data-button="Final Stage">So what?! &nbsp;</li>
  <li data-id="step4" data-button="Watch the demo!">Thats great isn't it?! &nbsp;</li>
  <li data-id="step5" data-button="Welcome! :)" data-options="tipLocation:bottom;tipAnimation:fade">Enjoy! &nbsp;</li>
</ol>
 -->
 
 <!-- Main Content -->
 <?php 
 $registered = Zend_Controller_Front::getInstance()->getRequest()->getParam('register');// $this->_request->getParam('register');
    	if ($registered == "true")
    	{
    		//$this->_helper->flashMessenger->addMessage("You have successfully registered at Social Green Project!");
    		//$this->messages =$aMessages = $this->_helper->FlashMessenger->getMessages();
    		echo "<div class='seven columns'>";
    		echo '<div class="alert-box">You have successfully registered at Social Green Project!<a href="" class="close">&times;</a></div>';
    		echo "</div>";
    	}
 
 ?>
<?php if (count($this->messages) > 0) {
			echo "<div class='seven columns'>";
			echo "<div class='alert-box'>". $this->messages[0].'<a href="" class="close">&times;</a></div>';
			echo "</div>";
}?>


<div class="row">
	<div class="twelve columns">
	<div id="description">
		<div class="row">
	  		<div id="MainTitles" class="four columns MainTitles" >
	  			Web Platform
	  		</div>
	 	</div>
 	
	 	<div class='row'>
	  		<div  class="twelve columns">
	  			<img style="width: 100%;" src="<?php echo $this->baseUrl("images/social-grid.png")?>"/>
	  		</div>
		</div>
		
		<div class="row">
			<div class="four columns"></div>
			<div class="four columns MainTitles">
	  			smart bins
	  		</div>
	  	</div>
	</div> 
	<!-- End of div#description -->
	</div>
</div>  
 <!-- End Main Content -->
 
 

<div style="padding-top:20px" class="row">
	
	<p class="MainTitles">Alex goes Social Green</p>
    <div class="seven columns centered">
		<iframe src="http://player.vimeo.com/video/55985914" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
	</div>
</div>
<div id='step5'></div>
  	
<!-- JoyRide code --> 
<!--  <script>	style="border:5px solid gray;border-radius: 2px;"
  $(window).load(function() {
    $("#chooseID").joyride({
      /* Options will go here */
   	 'tipLocation': 'top', 
    });
  });
</script>
 -->
  

<?php /* 
$db = Zend_db::factory('Mysqli',
		array(
				"host"=>"db6.papaki.gr",
				"dbname"=>"sg-alpha",
				"username"=>"terminaluser",
				"password"=>"hamburger"
				));

$data = $db->fetchAll("SELECT * FROM activity");

//echo "<p>Temp table</p><table border=1>";
foreach ($data as $row){
	//echo "<tr><td>Record id: ".$row['id']."</td><td>User ID: ".$row['userid']."</td><td>Quantity: ".$row['quantity']."</td><td>Date: ".$row['date']."</td></tr>";
}
//echo "</table>";
*/?>
