 <div class="row">
 	<div >
		<div class="span6 offset3">
			<div class="pagination-centered">
				<img src='<?php echo $this->baseUrl("images/logo 400px.png"); ?>'>
			</div>
			<div class="well" style="text-align:center;" >
				<h2>Site is currently under heavy construction!</h2>
				<p>The team is working hard to make an alpha version very soon!</p>
				
				<div class="progress progress-success progress-striped active">
  					<div class="bar" style="width: 20%;"></div>
				</div>
			</div>
		</div>
	</div>
</div>



