  <!-- First Band (Slider) -->
	  <!-- The Orbit slider is initialized at the bottom of the page by calling .orbit() on #slider -->
	    
	   <!-- First Band (Image) -->

		  <div class="row">
		  <div class="eight columns">
		      <h1>Welcome to Social Green Project!</h1>		      
		      <p>SocialGreen project is a social aware recycling system which combines the strength of social networks and the high smartphone penetration. The project provides a total free service to the users motivating them in recycling contribution. Taking advantage the rapid growth of the smartphone and Internet users, SocialGreen offers to our customers a tremendous marketing potential.</p></div>
		    
		    <div class="four columns">
		      <img src="images/leafs.png" />
		    </div>
		  </div>
  
  <div class="row">
  	<div class="twelve columns">
  		<p>Specifically it combines three of the most popular advertising channels; outdoor-web-mobile advertisement. Additionally our system could be used as a city-branding element, in any municipality or urban region, worldwide in order to elevate its echo-friendly profile.</p>
  		<p>The system is comprised of 3 main components; smart-recycling terminals, mobile applications and web application. It is specially developed in order to be user-friendly by providing a simple and clear use case. Using many of the most popular technologies as a solid foundation, it provides high technological viability.</p>
  	</div>
  </div>
  
  
<!-- Second Band (Image Left with Text) -->

  <div class="row">
    <div class="seven columns flex-video widescreen vimeo">
      <iframe src="http://player.vimeo.com/video/55985914" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
    </div>
    <div class="five columns">
      <h4>Promo Video</h4>
      <div class="row">
        <div class="twelve columns">
<p>SocialGreen tries to dominate recycling market, using smart ICT solutions. The whole system will be offered as a service to targeted users and customers. The core revenue for our project results from the advertising (physical or digital) space that we offer.
The eco-friendly, rewarding and ICT-based nature which characterizes SocialGreen can easily outbalance the existing competitors. It is quite rare to see such a system of this category that offers so many services to both users and customers.</p>
        </div>
      </div>
    </div>
  </div>


  <!-- Third Band (Image Right with Text) -->

  <div class="row">
    <div class="twelve columns">
      <h4>Social Green Project wins.. <img src="images/ennovation.png" /></h4>
      </div>
  </div>

<?php 
$db = Zend_db::factory('Mysqli',
		array(
				"host"=>"db6.papaki.gr",
				"dbname"=>"sg-alpha",
				"username"=>"terminaluser",
				"password"=>"hamburger"
				));

$data = $db->fetchAll("SELECT * FROM activity");

//echo "<p>Temp table</p><table border=1>";
foreach ($data as $row){
	//echo "<tr><td>Record id: ".$row['id']."</td><td>User ID: ".$row['userid']."</td><td>Quantity: ".$row['quantity']."</td><td>Date: ".$row['date']."</td></tr>";
}
//echo "</table>";
?>
