<div class="row">
		<div class="span6 offset3">
			<h1>Attention!</h1>
			<p>At the moment Social Green is under Development! But we will keep you updated with upcoming changes!</p>
		</div>
</div>
<div class="row">
	
	<div class="span6 offset3">
		<?= $this->Errors($this->errors); ?>
 		<h1>Login</h1>
		<?php echo $this->form->setAction($this->url()); ?>
		<p>- or -<br>
		<button id="fbc-login-button">Login with Facebook</button>
		</p>
	</div>
	<div class="span3">
	</div>
</div>

