<!-- <div class="row">
	<div class="six columns offset-by-three">
 		<h1>Login</h1>
		<?php //echo $this->form->setAction($this->url()); ?>
	</div>
	<?= $this->Errors($this->errors); ?>
</div>-->

<div class="row">
		<div class="six columns offset-by-three panel">
			<h1>Attention!</h1>
			<p>At the moment Social Green is under Development! But we will keep you updated with upcoming changes!</p>
		</div>
</div>