<?php  $badges = $this->badges; ?>
<?php $badgesPrefix = $this->badgesPrefix; ?>

<?php /*<div class="row-fluid userContent">
	<div class="span12">
	<h2>Badges of Sociallgreen 1</h2>
	
	<?php 
		$counter = 1; 
				
		foreach ($badges as $badge) 
		{ 
			if (($counter % 2) == 1)
			{ ?>
				<!-- Arxi siras -->
				<hr>
				<div class="row-fluid">
				<div class="span6">
				
				<div class="row-fluid">
					<div class="span4 text-center">
						<img class="badges" src="<?php echo $this->baseUrl($badgesPrefix.$badge->path); ?>">
						<h3><?php echo $badge->title; ?></h3>
					</div>
					<div class="span8">
						<p><?php echo $badge->description; ?></p>
					</div>
				</div>
				</div>
				
			<?php
			}
			else
			{ ?>
				
				<div class="span6">
				<div class="row-fluid">
					<div class="span4 text-center">
						<img class="badges" src="<?php echo $this->baseUrl($badgesPrefix.$badge->path); ?>">
						<h3><?php echo $badge->title; ?></h3>
					</div>
					<div class="span8">
						<p><?php echo $badge->description; ?></p>
					</div>
				</div>
				</div>
				</div>
			<?php
			} 
			$counter++; 
		}
		if (($counter % 2) == 1)
		{
			echo "</div>";
		}
		?>	
			
	</div>
</div> */ ?>

<div class="row-fluid userContent">
	<div class="span12">
	<h2> Sample Badges</h2>
	
	<?php 
		$counter = 1; 
				
		foreach ($badges as $badge) 
		{ 
			if (($counter % 2) == 1)
			{ ?>
				<!-- Arxi siras -->
				<hr>
				<div class="row-fluid">
				<div class="span6">
				
				<div class="row-fluid">
					<div class="span4 text-center">
						<img class="badges2" src="<?php echo $this->baseUrl($badgesPrefix.$badge->path); ?>">
					</div>
					<div class="span8">
						<h3 class="text-badges"><?php echo $badge->title; ?></h3>
						<p><?php echo $badge->description; ?></p>
					</div>
				</div>
				</div>
				
			<?php
			}
			else
			{ ?>
				<div class="span6">
				<div class="row-fluid">
					<div class="span4 text-center">
						<img class="badges2" src="<?php echo $this->baseUrl($badgesPrefix.$badge->path); ?>">
					</div>
					<div class="span8">
						<h3 class="text-badges"><?php echo $badge->title; ?></h3>
						<p><?php echo $badge->description; ?></p>
					</div>
				</div>
				</div>
				</div>
			<?php
			} 
			$counter++; 
		}
		if (($counter % 2) == 1)
		{
			echo "</div>";
		}
		?>			
	</div>
</div>
		
				
		