<div class='row'>
	<div class="span6 offset3">
		<img src='<?php echo $this->baseUrl('images/verified.png') ?>'>
	</div>
</div>
<div class='row'>
	<div class="span6 offset3">
		<h1>Your account is now verified!</h1>
		<p>Welcome back <?php echo $this->user; ?>! You have successfully registered at Social Green Project!</p>
		<p>Now you can just login using your credentials at <a href="<?php echo $this->url(array('controller'=>'auth'), null, TRUE) ?>">login section</a>!</p>
    </div>
</div>