<?php  $accounts = $this->accounts; ?>
<div class="row-fluid">
	<div class="span4">
		<div class="span12">
			<h3><strong>234</strong><br>Total leafs saved today</h3>
		</div>
		<hr>
		<div class="span12">
			<h5>Friends Section</h5>
			<?php $counter=0;?>
			<?php  foreach ($accounts as $account) { ?>
				
				<div class="media span3 friends">
				 
				  <a class="thumbnail" title="<?php echo $account->username; ?>" href="#">
				    <img class="media-object" src="http://placehold.it/50x50&text=Thumbnail">
				  </a>
				  <div class="media-body">
				   <?php //echo $account->username; ?>
				  </div>  
				<?php if ($counter==0) { echo '<span class="left label label-info newMember">New!</span>'; }
				elseif ($account->points>2) {  echo '<span class="left label label-success newMember"><i class="icon-leaf icon-white"></i></span>';}?>
				</div>
				
			 <?php $counter++; } ?>	
		</div>
	</div>
	<div class="span5">
		<div class="row">
			<ul class="nav nav-pills">
			  <li class="active">
			    <a  data-toggle="tab" href="#home">Home</a>
			  </li>
			  <li><a  data-toggle="tab" href="#profile">profile</a></li>
			</ul>
            <div id="myTabContent" class="tab-content">
              <div class="tab-pane fade active in" id="home">
                <div id="barChartContainer" style="min-width: 400px; height: 400px; margin: 0 auto"></div>
              </div>
              <div class="tab-pane fade" id="profile">
                <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
              </div>
            </div>
       
			
		</div>	
	</div>
</div>
