<?php  $accountsFriends = $this->accounts; ?>
<?php $activeUser = $this->activeAccount; ?>
<?php  $accounts = $this->accounts; ?>
<?php $userbadges = $this->userbadges;?>
<?php  //$auth = Zend_Auth::getInstance();
		//$username = $auth->getIdentity()->username;?>
<?php $imgPrefix = $this->imgPrefix; ?>
<?php $badgesPrefix = $this->badgesPrefix; ?>
<?php 
	$sum=0;
	foreach ($this->allActivity as $activityTemp){
	//$sum = $sum +  (1*$activityTemp->glass)+(2*$activityTemp->plastic)+(3*$activityTemp->aluminium);
	$sum = $sum + $activityTemp->leafs;
}?>

<?php  foreach ($accounts as $account) {      	
       		if($account->username == $activeUser) { 
				$leafs = $account->leafs;
			}
		}
?>

<div class="row-fluid userContent">
	<div class="span3">
		
		<div class="row-fluid">
			<div class="span11 " id="friends" style="margin-top: 120px;">
				<div id="profile-points" class="row-fluid profile-points">
					<div class="span11">
						<div class="profile-points ">
							<span>leaves<br>saved</span>
						</div>
					</div>
					<div class="span11">
						<div class="profile-points ">
							<span><?php echo $leafs;?></span>
						</div>
					</div>
				</div>
			</div>
			
			<div class="span11" id="friends" style="margin-top: 30px;">
				
				<h5><span class="other-titlos">Other users</span></h5>
				
				
				<?php $counter = 0; 
				$mostPoints = 0;
				?>
				<?php  foreach ($accountsFriends as $account) { ?>
				<?php if ($counter==0) $mostPoints = $account->quantity; ?>
					<div class="span2">
						  <a class="thumbnail" title="<?php echo $account->username; ?>" href="<?php echo $this->baseUrl('account/profile/').'?user='.$account->username;?>">
						    <span class="right visible-phone"><?php echo $account->username; ?></span>
  						    <img class="media-object" src="<?php echo $this->baseUrl($imgPrefix."thumb-".$account->avatar); ?>">
						  </a>
						<?php //if ($counter==0) { echo '<span class="left label label-info newMember">New!</span>'; }
						//elseif ($account->quantity>0.8*$mostPoints) {  echo '<span class="left label label-success newMember"><i class="icon-leaf icon-white"></i></span>';}?>
					</div>
				 <?php 
				 $counter++; 
				} ?>	
			</div>
		</div>
		
	</div>
	<div class="span6 offset0">
	<?php  foreach ($accounts as $account) {      	
       	if($account->username == $activeUser) { ?>
		<div class='row-fluid '>
			<div class="span12">
				 <img class="profile-photo media-object" src="<?php echo $this->baseUrl($imgPrefix.$account->avatar); ?>">
			</div>
		</div>
		<div class='row-fluid '>
			<div class="span6">
				<div class="row-fluid">
					<p><?php echo $account->description; ?></p>
				</div>
				
			</div>
			<div class='span6'>
				<table class="table table-striped">
					<tbody>
					<tr><td><p>Total leafs saved: <span class="text-success"><strong><?php echo 1*$account->glass+2*$account->plastic+3*$account->aluminium; ?></strong></span></p></td></tr>
					<tr><td><p>Last recycled on: <?php echo date("F j, Y",strtotime($account->date)); ?></p></td></tr>
					<tr>
					<td>
					<span class="customh4" ><a href='<?php echo $this->baseUrl('account/badges'); ?>' title='badges' >Badges</a></span><br>
					<hr class="btable">
					<?php 
						$counter = 1; 		
						foreach ($userbadges as $badge) 
						{?>
							<img class="badges" title="<?php echo $badge->title; ?>" src="<?php echo $this->baseUrl($badgesPrefix.$badge->path); ?>"></img>
							<?php
						}
						?>
						</td>
						</tr>
					</tbody>
				</table>
				 
				<hr>
				<p><a href='<?php echo $account->url; ?>' target="_blank" class="btn btn-success">Go to&nbsp;<?php echo $account->url; ?></a></p>
			</div>
		</div>
		<!-- 
		<div class="row-fluid">
			<div class="progress">
				<div class="bar bar-success" style="width: <?php echo ($account->quantity/$mostPoints)*100 ?>%;"><?php echo $account->quantity;?> points</div>
			</div>
		</div>
		 -->
	<?php } } ?>
		
	</div>
</div>

