<div class="row-fluid span8 offset2">
<form id="quiz" action="<?= $this->element->getAction(); ?>" method="<?= $this->element->getMethod(); ?>">
   <div id="Quizfooter" class="row">
   		<div class="progress progress-success">
	  		<div id="questionBar" class="bar" style="width:0%"></div>
		</div>
   		<ul class="pager">
  			<li><a id="back" href="#">Previous</a></li>
  			<li><a id="next" href="#">Next</a></li>
		</ul>
		
   	</div>
   
   <div id="q_1_container" active="true">
   		<h2>Question 1</h2>
   		<p><?= $this->element->q_1; ?></p>
   </div>
   <div id="q_2_container" class="hidden">
   		<h2>Question 2</h2>
   		<p><?= $this->element->q_2; ?></p>
   </div>
   <div id="q_3_container" class="hidden">
   		<h2>Question 3</h2>
   		<p><?= $this->element->q_3; ?></p>
   </div>
   <div id="q_4_container" class="hidden">
   		<h2>Question 4</h2>
   		<p><?= $this->element->q_4; ?></p>
   </div>
   <div id="q_5_container" class="hidden">
   		<h2>Question 5</h2>
   		<p><?= $this->element->q_5; ?></p>
   </div>
   <div id="submit_container" class="hidden">
   <p>Thank you for your time!</p>
   		<?= $this->element->submit;?>
   		<hr>
   		<p>You can also provide an e-mail so as to inform you about future updates!</p>
   		<p><a title="Feedback!" class="btn btn-info" href="#contactModal" data-toggle="modal">Complete the form!</a></p>
   </div>
</form>
</div>
<script>
	$("input.radio").change(function(){
			next(this);
		});
	$("form#quiz").submit(function(){
			var data = $(this).serialize();
			var url = '<?php echo $this->baseUrl("/about/submit-Quiz/"); ?>';
			$("input#submit").attr("value", "Processing...");
			$("input#submit").attr("class", "btn btn-success");
			$.ajax({
			  type: "POST",
			  url: url,
			  data: data,
			  success: function(resp){
				  if (resp=="1"){
				  	$("input#submit").attr("value", "Your answers are saved!");
				  } else {
					  $("input#submit").attr("value", "Error during processing");
					  $("input#submit").attr("class", "btn btn-warning");
				  }
			  }
			});
			return false;
	});

	$("a#back").click(function (){
		var $item = $("form#quiz").find("div[active=true]");
		$item.attr("active","false");
		back($item.find("input[type=radio]"));
	});
	
	$("a#next").click(function (){
	 	$item = $("form#quiz").find("div[active=true]");
	 	$item.attr("active","false");
		next($item.find("input[type=radio]"));
	});
	
	function back($this){
		var question = $($this).attr("name");
		//alert(question)
		var container = question+"_container";
		$("#"+container).hide("slow", function(){
				name = question;
				toRemove = 'q_';
				id = name.replace(toRemove,'');
			 	toShow = "#"+"q_"+(parseInt(id)-1)+"_container";
				if (id=="5") { toShow="#submit_container";};
				$(toShow).show("slow").toggleClass("hidden");//show("slow");
				$(toShow).attr("active","true");
				$("#questionBar").css("width",2*parseInt(id)+"0%");
			});
	}

	function next($this){
		var question = $($this).attr("name");
		var container = question+"_container";
		$("#"+container).hide("slow", function(){
				$(this).attr("active","false");
				var name = question;
				var toRemove = 'q_';
				var id = name.replace(toRemove,'');
				var toShow = "#"+"q_"+(parseInt(id)+1)+"_container";
				if (id=="5") { toShow="#submit_container";};
				$(toShow).show("slow").toggleClass("hidden");//show("slow");
				//alert("width:"+2*parseInt(id)+"0%");
				$(toShow).attr("active","true");
				$("#questionBar").css("width",2*parseInt(id)+"0%");
			});
	}
</script>