<form id="register" action="<?= $this->element->getAction(); ?>"
method="<?= $this->element->getMethod(); ?>">
    <p>
        Username:<br>
        <?= $this->element->username; ?>
    </p>
<p>
E-mail Address:<br />
<?= $this->element->email; ?>
</p>
<p>
Password:<br />
<?= $this->element->pswd; ?>
</p>
<p>
Password retype:<br />
<?= $this->element->pswd2; ?>
</p>

<?php /*
<p>
Profile Photo:<br />
<?= $this->element->file; ?>
</p>
*/?>
<p>
Description:<br />
<?= $this->element->description; ?>
</p>

<p>
<?= $this->element->submit; ?>
</p>
</form>