<html>
    <head>
    	<meta charset="utf-8" />
  		<?php echo $this->headTitle($this->title); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <link href='http://fonts.googleapis.com/css?family=Stalemate' rel='stylesheet' type='text/css'>
    	<!-- Bootstrap -->
    	<?php  $this->headLink()->appendStylesheet($this->baseUrl('bootstrap/css/bootstrap.min.css')); ?>
    	<?php  $this->headLink()->appendStylesheet($this->baseUrl('css/mainStyle.css')); ?>
    	<?php echo $this->headLink(); ?>
    </head>
<body >

<!-- Navbar
    ================================================== -->
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="brand" title="Back to home" href="<?php echo $this->url(array('controller'=>'index'), null, TRUE); ?>"><img id="logo" src="<?php echo $this->baseUrl("images/logo50.png"); ?>"></a>
			<div class="nav-collapse collapse">
				<ul class="nav pull-right">
				<?php
				$uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); 
				$howItworks=""; $getInvolved="";
				if ($uri == $this->url(array('controller'=>'about', 'action'=>'how-it-works'), null, TRUE) )
				{
					//$howItworks= "class='active'";
				}else if ($uri == $this->url(array('controller'=>'about', 'action'=>'get-involved'), null, TRUE) )
				{
					//$getInvolved= "class='active'";
				}?>
				
					<?php /*<li <?= $howItworks ?> ><a title="Learn more!" href="<?php echo $this->url(array('controller'=>'about', 'action'=>'how-it-works'), null, TRUE); ?>">How It Works</a></li>
					<li <?= $getInvolved ?>><a title="Participate!" href="<?php echo $this->url(array('controller'=>'about', 'action'=>'get-involved'), null, TRUE); ?>">Get Involved</a></li> */ ?> 
					<li <?= $howItworks ?> ><a title="Learn more!" style="text-decoration:line-through;" >How It Works</a></li>
					<li <?= $getInvolved ?>><a title="Participate!" style="text-decoration:line-through;" >Get Involved</a></li>
					
				</ul>
				<!-- POP UP menu for later.. 
				<ul class="nav pull-right">  
					<li class="dropdown">  
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Services
					<b class="caret"></b>  
					</a>  
					<ul class="dropdown-menu">  
						<li><a href="#">Web Design</a></li>  
						<li><a href="#">Web development</a></li>  
						<li><a href="#">Wordpress Theme development</a></li>  
					</ul>
					</li>
				</ul>
				 -->
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>
<!-- End of Navbar -->

<!-- View Content
    ================================================== -->
   
<div class="container" id="mainContent">
	<?php echo $this->layout()->content; ?>
</div>
<!-- End of View Content -->
	
<!-- Footer 
    ================================================== -->
<div class="container ">
<div class="row pagination-centered ">
    	<hr />
      	<div class="row offset3">
	      	<!-- ABOUT -->
	      	<div class="span2">
	      		<ul class="mylist">
		        	<li class="FooterTitles">Info</li>
					<li ><a title="Learn about us!"  href="<?php echo $this->url(array('controller'=>'about', 'action'=>'ourteam'), null, TRUE); ?>" >About</a></li>
					<li ><a title="Dig in our project!"  href="<?php echo $this->url(array('controller'=>'about', 'action'=>'how-it-works'), null, TRUE); ?>" >How it works</a></li>
					<li ><a title="Legal staff!" style="text-decoration:line-through;" >Terms &amp; Privacy</a></li>
				</ul>
	       	</div>
	        
	       	<!-- Activities -->
	        <div  class="span2">
				<ul class="mylist">
					<li class="FooterTitles">Activities</li>
					
					<li><a title="Contribute!" href="<?php echo $this->url(array('controller'=>'about', 'action'=>'quiz'), null, TRUE); ?>">Get the quiz</a></li>
					<li><a title="Participate!" style="text-decoration:line-through;" >Get Involved</a></li>
					<li><a title="Feedback!" href="#contactModal" data-toggle="modal">Contact us</a></li>
					<!-- href="/underdevelopment/public/auth"  -->
				</ul>
	        </div>
	        <!-- Find Us -->
	        <div class="span2">
	        	<ul class="mylist">
					<li class="FooterTitles ">Social</li>
					
					<!-- VERSION with Likes and follows
						================================================== 
					<li class="social">
					<!-- LinkedIn 
    					================================================== 
						<script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
						<script type="IN/FollowCompany" data-id="2937639" data-counter="right"></script>
					</li>
					<li><div class="fb-like" data-href="http://www.facebook.com/SGreenProject" data-send="false" data-layout="button_count" data-width="100" data-show-faces="true" data-font="arial"></div></li>
					<li><a href="https://twitter.com/SGreen_Project" class="twitter-follow-button" data-show-screen-name="false" data-width="120px"  data-show-count="true" data-lang="en">Follow Us</a></li>
					-->
					
					<!-- VERSION Images with links to social 
						================================================== -->
		          	<li><a title="See our LinkedIn" target="_blank" href="http://www.linkedin.com/company/2937639?trk=tyah"><img  class='img-rounded social' src="<?php echo $this->baseUrl('images/fairhead-icons/fc-webicon-linkedin-m.png'); ?>"></a></li>
		            <li><a title="Check our facebook" target="_blank" href="https://www.facebook.com/SGreenProject"><img  class='img-rounded social' src="<?php echo $this->baseUrl('images/fairhead-icons/fc-webicon-facebook-m.png'); ?>"></a></li>
					<li><a title="Follow us on Twitter" target="_blank" href="https://twitter.com/SGreen_Project"><img  class='img-rounded social' src="<?php echo $this->baseUrl('images/fairhead-icons/fc-webicon-twitter-m.png'); ?>"></a></li>
					
				</ul>
	        </div>
        </div>
    	<div class="span12">
      		<p class="FooterTitles" style="text-decoration: none;">&copy; Copyright 2013 Social Green</p>
      	</div>
      	
</div>
</div>
<!-- End of Footer -->

<!-- Google Analytics 
    ================================================== -->
 <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36877660-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
 
<!-- facebook Like 
    ================================================== 
	<div id="fb-root"></div>
	<script>(
	function(d, s, id)
	{
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/el_GR/all.js#xfbml=1";
		fjs.parentNode.insertBefore(js, fjs);
	}
	(document, 'script', 'facebook-jssdk'));
	</script>
-->

<!-- Twitter Follow
    ================================================== 
    <script>!function(d,s,id){
        var js,fjs=d.getElementsByTagName(s)[0];
        if(!d.getElementById(id))
        {
            js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js,fjs);
        }
        }(document,"script","twitter-wjs");
	</script>
-->
    
   <!-- Contact Form -->
<div id="contactModal" class="modal hide fade"  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
    <h3 id="myModalLabel" class="hidden-phone">Contact Form</h3>
  </div>
  <div class="modal-body">
    <?php echo $this->action("submit-contact", "index");// contactForm; ?>
  </div>
</div>  
    
 <!-- BootStrap & Jquery Script 
     ================================================== -->
 <script src="http://code.jquery.com/jquery.js"></script>
 <script src="<?php echo $this->baseUrl("bootstrap/js/bootstrap.min.js"); ?>"></script>
 <script type="text/javascript">
 			$(document).ready(function () {
    			$("a").tooltip();
  			});
		</script>
</body>
<!-- HITSNIFFER TRACKING CODE - Manual 2013-03-28 - DO NOT CHANGE -->
<script>aid=22717;sid=24435;</script>
<script type="text/javascript">(function(){var hstc=document.createElement('script');var hstcs='www.';if (document.location.protocol=='https:') hstcs='';hstc.src=document.location.protocol+'//'+hstcs+'hitsniffer.com/track.js';hstc.async=true;var htssc = document.getElementsByTagName('script')[0];htssc.parentNode.insertBefore(hstc, htssc);})();
</script><noscript><a href="http://www.hitsniffer.com/"><img src="http://www.hitsniffer.com/track.php?mode=img&amp;code=c4d04a7b314ac20dbe6b55a6a3207ca5" alt="web stats" />web statistics</a></noscript>
<!-- HITSNIFFER TRACKING CODE - DO NOT CHANGE -->

<!-- BugSense Code -->
 <script src="http://www.bugsense.com/static/js/global/bugsense.js" type='text/javascript'></script>
 <script type="text/javascript">
    var bugsense = new Bugsense( { apiKey: 'a66b52fb' } );
 </script>
 <!-- End of BugSense -->
</html>