<div class="row-fluid ">
	<div class="span2 offset2" >
				<h2 class=""><span class="purplefonts">Social</span><span class="greenfonts">Green</span></h2>
				</div>
				<div class="span4" >
				<p>He has graduated from the Department of Economics of Aristotle university. 
				During those years he attended student exchange programmes in Sweden and France gaining multicultural experiences. 
				By October 2012 he holds an MSc at "Informatics and Management" from the Computer Science Departement of Aristotle. 
				His working experience include traineeships at Greek ministry of foreign affairs, Hellenic post bank and a Consulting company. 
				He is a co-founder of SocialGreen where he works on the Business Development of the project.</p>
				<button class="btn btn-large btn-primary" type="button">Host the pilot version!</button>
	</div>
</div>
