<?php /*<div class="row-fluid ">
	<div class="span2 offset2" >
				<h2 class=""><span class="purplefonts">Social</span><span class="greenfonts">Green</span></h2>
				</div>
				<div class="span4" >
				<p>He has graduated from the Department of Economics of Aristotle university. 
				During those years he attended student exchange programmes in Sweden and France gaining multicultural experiences. 
				By October 2012 he holds an MSc at "Informatics and Management" from the Computer Science Departement of Aristotle. 
				His working experience include traineeships at Greek ministry of foreign affairs, Hellenic post bank and a Consulting company. 
				He is a co-founder of SocialGreen where he works on the Business Development of the project.</p>
				<button class="btn btn-large btn-primary" type="button">Host the pilot version!</button>
	</div>
</div>--------------

<div class="row-fluid ">
	<div class="span8 offset2" >
				<h2 class="text-center" >Are you an Organisation ?</h2>
				
				<p class="text-center" >Want to enagage your people into recycling ?</p>
				<br>
				
	</div>
</div>
<div class="row-fluid ">
	<div class="span3 offset2" >
		<h3>What is the bin?</h3>
		<img class="img-polaroid" style="width:200px;margin:0px 2px;" src="<?php echo $this->baseUrl("images/teamPhotos/photos/mikres/antw.jpg"); ?>">
	</div>
	<div class="span4 " style="margin-top:60px;" >
		<blockquote>
		<p>He has graduated from the Department of Economics of Aristotle university. 
		</p>
		<br>
		</blockquote>
	</div>
</div>
<div class="row-fluid ">
	<div class="span4 offset2 " style="margin-top:60px;">
		<blockquote class="pull-right">
		<p>He has graduated from the Department of Economics of Aristotle university. 
		</p>
		<br>
		</blockquote>
	</div>
	<div class="span3 text-right" style="margin-bottom: " >
		<h3>Where can i get one?</h3>
		<img class="img-polaroid pull-right" style="width:200px;margin:10px 2px;" src="<?php echo $this->baseUrl("images/teamPhotos/photos/mikres/antw.jpg"); ?>">
	</div>
</div>
<div class="row-fluid ">
	<div class="span3 offset2" >
		<h3 class="text-left">What do i win?</h3>
		<img class="img-polaroid" style="width:200px;margin:10px 2px;" src="<?php echo $this->baseUrl("images/teamPhotos/photos/mikres/antw.jpg"); ?>">
	</div>
	<div class="span4 " style="margin-top:60px;" >
		<blockquote>
		<p >He has graduated from the Department of Economics of Aristotle university. </p>
		<br>
		</blockquote>			
	</div>
</div>
<div class="row-fluid ">
	<div class="span4 offset4" >
		<button class="btn btn-large btn-primary" type="button">Interested?</button>
	</div>
</div>
*/?>
<div class="row-fluid " style="margin-top: 50px;">
	<div class="span6 offset5" >
				<h2  >Are you an Organisation ?</h2>
				
				<p  >Want to enagage your people into recycling ?</p>
				<br>
				
	</div>
</div>
<div class="row-fluid ">
	<div class="span3 offset2" >
		<h3 class="text-left" style="font-size:17pt; margin:0px;">The Sociallbin</h3>
		<img class="" style="width:200px;margin:0 0 10px 0px;" src="<?php echo $this->baseUrl("images/sketch/kados.png"); ?>">
		<blockquote>
		<p>He has graduated from the Department of Economics of Aristotle university. </p>
		<br>
		</blockquote>
	</div>

	<div class="span3">
		
		<button  class="btn btn-large btn-primary" style="margin-top:40px;margin-right: 0px;" type="button">Interested?</button>
		
		<!-- 
		<div style="margin-top:80px;">
		<h3 style="font-size:17pt; margin:0px;">Where can i get one?</h3>
		<img class=" " style="width:200px;margin:0 0 10px 0px;" src="<?php echo $this->baseUrl("images/sketch/kados.png"); ?>">
		<blockquote>
		<p>For the time being
		</p>
		<br>
		</blockquote>
		</div>
		 -->
	</div>

	<div class="span3 " >
		<h3 style="font-size:17pt;margin:0px;">What do i win?</h3>
		<img class=" " style="width:200px;margin:0 0 10px 0px;" src="<?php echo $this->baseUrl("images/teamPhotos/photos/mikres/antw.jpg"); ?>">
		<blockquote>
		<p>He has graduated from the Department of Economics of Aristotle university. </p>
		<br>
		</blockquote>			
	</div>
</div>


