<?php /*

<!--Sticky Sidenav, and sketch content
    ==================================================-->

<div class="row" >
	<div class="span3 bs-docs-sidebar">
		<ul class="nav nav-tabs nav-stacked " > 
		<?php foreach ($this->information as $item) {?>
			<li>
				<a href="#<?php echo $item['id']; ?>" data-toggle="tab" ><i class="icon-chevron-right"></i><?= $item['linktitle']?></a>
    		</li>
    		<?php } ?>
    	</ul>
    </div>
    <div class="tab-content">
    	<?php foreach ($this->information as $dataitem) {?>
	   <div class="span9 tab-pane <?php if ($dataitem['id2']=="firstStep") echo "active"; ?>" id="<?php echo $dataitem['id2']; ?>" > 
	        <section>
		        <!-- <div class="page-header">
		        	<h1>5th Step</h1>
		        </div> -->
		        <div class="row">
		        	<div class="span3 offset1">
		        		<img class="sketch" src='<?php echo $this->baseUrl("images/sketch/".$dataitem['image']); ?>'>
		        	</div>
		        	<div class="span3 sketchText">
		        		<?php echo $dataitem['text']; ?>
		        	</div>
		        </div>
	        </section>
		</div>
		<?php } ?>
	</div>
    
</div>

<!-- End of Sticky Sidenav, and sketch content
    ==================================================-->
*/ ?>
<div class="row">
<div class="span10 offset1 " style="background:rgba(0, 0, 0, 0.75);">
<div id="myCarousel" class="carousel slide">
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
		<li data-target="#myCarousel" data-slide-to="3"></li>
		<li data-target="#myCarousel" data-slide-to="4"></li>
	</ol>
	<!-- Carousel items -->
	<div class="carousel-inner">
	<?php foreach ($this->information as $dataitem) {?>
	
		<div class="item <?php if ($dataitem['id2']=="firstStep") echo "active"; ?>">
			<div class="row pagination-centered">
			<div class="span6 offset2">
				<img class="sketch" src='<?php echo $this->baseUrl("images/sketch/".$dataitem['image']); ?>'>
			</div>
			</div>
			<div class="carousel-caption sketchText">
				<?php echo $dataitem['text']; ?>
			</div>
		
		</div>
	<?php } ?>
	</div>
	<!-- Carousel nav -->
	<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="carousel-control right" href="#myCarousel" data-slide="next" >&rsaquo;</a>
</div>
</div>
</div>	
	
	

