<!-- <div  data-target="bs-docs-sidebar" data-spy="scroll" data-twttr-rendered="true" >  --> 


<!--Sticky Sidenav, and sketch content
    ==================================================-->

<div class="row" >
	<div class="span3 bs-docs-sidebar">
		<ul class="nav nav-list bs-docs-sidenav affix" >
			<li class="">
				<a href="#firstStep"><i class="icon-chevron-right"></i>First Step</a>
    		</li>
    		<li class="">
    			<a href="#secondStep">
    			<i class="icon-chevron-right"></i>Second Step</a>
    		</li>
    		<li class="">
    			<a href="#thirdStep">
    			<i class="icon-chevron-right"></i>Third Step</a>
    		</li>
    		<li class="">
    			<a href="#fourthStep">
    			<i class="icon-chevron-right"></i>Fourth Step</a>
    		</li>
    		<li class="">
    			<a href="#fifthStep">
    			<i class="icon-chevron-right"></i>Fifth Step</a>
    		</li>
    	</ul>
    </div>
    
	<div class="span9">
    
    	<!-- First Step
        ================================================== -->
    	<section id="firstStep">
	    	<div class="page-header">
	        	<h1>First Step <small>for smart recycle</small></h1>
	        </div>
	    	<h3>About transitions</h3>
		        <p>For simple transition effects, include 
		    		<strong>bootstrap-transition.js</strong>
		      	 	once alongside the other JS files. If you're using the compiled (or minified) 
		      	 	<strong>bootstrap.js</strong>
					, there is no need to include this—it's already there.
				</p>
			    <h3>Use cases</h3>
			    <p>	A few examples of the transition plugin:</p>
			    <ul>
			    	<li>Sliding or fading in modals</li>
			    </ul>
    	</section>
    
    	<!-- Second Step
        ==================================================-->
        
        <section id="secondStep">
	        <div class="page-header">
	        	<h1>Second Step <small> kati exypno</small></h1>
	        </div>
	        <h3>About transitions</h3>
	        <p>For simple transition effects, include 
	    		<strong>bootstrap-transition.js</strong>
	      	 	once alongside the other JS files. If you're using the compiled (or minified) 
	      	 	<strong>bootstrap.js</strong>
				, there is no need to include this—it's already there.
			</p>
		    <h3>Use cases</h3>
		    <p>	A few examples of the transition plugin:</p>
		    <ul>
		    	<li>Sliding or fading in modals</li>
		    </ul>
        </section>
        
        <!-- Third Step
        ==================================================-->
        
        <section id="thirdStep">
	        <div class="page-header">
	        	<h1>Third Step <small> kati exypno</small></h1>
	        </div>
	        <h3>About transitions</h3>
	        <p>For simple transition effects, include 
	    		<strong>bootstrap-transition.js</strong>
	      	 	once alongside the other JS files. If you're using the compiled (or minified) 
	      	 	<strong>bootstrap.js</strong>
				, there is no need to include this—it's already there.
			</p>
		    <h3>Use cases</h3>
		    <p>	A few examples of the transition plugin:</p>
		    <ul>
		    	<li>Sliding or fading in modals</li>
		    </ul>
        </section>
        
        <!-- Fourth Step
        ==================================================-->
        
        <section id="fourthStep">
	        <div class="page-header">
	        	<h1>fourth Step <small> kati exypno</small></h1>
	        </div>
	        <h3>About transitions</h3>
	        <p>For simple transition effects, include 
	    		<strong>bootstrap-transition.js</strong>
	      	 	once alongside the other JS files. If you're using the compiled (or minified) 
	      	 	<strong>bootstrap.js</strong>
				, there is no need to include this—it's already there.
			</p>
		    <h3>Use cases</h3>
		    <p>	A few examples of the transition plugin:</p>
		    <ul>
		    	<li>Sliding or fading in modals</li>
		    </ul>
        </section>
        
        <!-- Fifth Step
        ==================================================-->
        
        <section id="fifthStep">
	        <div class="page-header">
	        	<h1>fifth Step <small> kati exypno</small></h1>
	        </div>
	        <h3>About transitions</h3>
	        <p>For simple transition effects, include 
	    		<strong>bootstrap-transition.js</strong>
	      	 	once alongside the other JS files. If you're using the compiled (or minified) 
	      	 	<strong>bootstrap.js</strong>
				, there is no need to include this—it's already there.
			</p>
		    <h3>Use cases</h3>
		    <p>	A few examples of the transition plugin:</p>
		    <ul>
		    	<li>Sliding or fading in modals</li>
		    </ul>
        </section>
    
	</div>
    
</div>

<!-- End of Sticky Sidenav, and sketch content
    ==================================================-->

</div>