<div  data-target="bs-docs-sidebar" data-spy="scroll" data-twttr-rendered="true" > 


<!--Sticky Sidenav, and sketch content
    ==================================================-->

<div class="row" >
	<div class="span3 bs-docs-sidebar">
		<ul class="nav nav-tabs nav-stacked " > 
			<li>
				<a href="#firstStep" data-toggle="tab" ><i class="icon-chevron-right"></i>1st Collect</a>
    		</li>
    		<li>
    			<a href="#secondStep" data-toggle="tab" ><i class="icon-chevron-right"></i>2nd Dispose</a>
    		</li>
    		<li >
    			<a href="#thirdStep" data-toggle="tab" ><i class="icon-chevron-right"></i>3rd Scan</a>
    		</li>
    		<li>
    			<a href="#fourthStep" data-toggle="tab" ><i class="icon-chevron-right"></i>4th Play</a>
    		</li>
    		<li>
    			<a href="#fifthStep" data-toggle="tab" ><i class="icon-chevron-right"></i>5th Win</a>
    		</li>
    	</ul>
    </div>
    <div class="tab-content">
    	
	    <!-- First Step
	    ================================================== -->
	    <div class="span9 tab-pane active" id="firstStep" >
	    	<section >
		    	<!-- <div class="page-header">
		        	<h1>1st Step</h1>
		        </div> -->
		          <div class="row">
		        	<div class="span5">
		    			<img class="sketch" src='<?php echo $this->baseUrl("images/sketch/pickup.png"); ?>'>
		    	   	</div>
		        	<div class="span3 sketchText">
		        		Search your place for cans, glass and the plastic bottles...
		        	</div>
		        </div>
	    	</section>
	    </div>
    
    	<!-- Second Step
        ==================================================-->
    	<div class="span9 tab-pane" id="secondStep" >    
	        <section >
		        <!-- <div class="page-header">
		        	<h1>2nd Step</h1>
		        </div> -->
		         <div class="row">
		        	<div class="span5">
		        		<img class="sketch" src='<?php echo $this->baseUrl("images/sketch/throw.png"); ?>'>
		         	</div>
		        	<div class="span3 sketchText">
		        		Go to the nearest bin, wake him up and throw. He will count for you...
		        	</div>
		        </div>
	        </section>
        </div>
        
        <!-- Third Step
        ==================================================-->
        <div class="span9 tab-pane" id="thirdStep" > 
	        <section >
		        <!-- <div class="page-header">
		        	<h1>3rd Step</h1>
		        </div> -->
		        <div class="row">
		        	<div class="span5">
		        		<img class="sketch" src='<?php echo $this->baseUrl("images/sketch/qrscan.png"); ?>'>
		        	</div>
		        <div class="span3 sketchText">
		        	Use the social green app to scan the QR code which contains your score...
		        </div>
		        </div>
	        </section>
		</div>
        
        <!-- Fourth Step
        ==================================================-->
        <div class="span9 tab-pane" id="fourthStep" > 
	        <section >
		        <!-- <div class="page-header">
		        	<h1>4th Step</h1>
		        </div> -->
		        <div class="row">
		        	<div class="span5">
		        		<img class="sketch" src='<?php echo $this->baseUrl("images/sketch/sync.png"); ?>'>
		        	</div>
		        	<div class="span3 sketchText">
		        		Go to sociallgreen.com find your friends, form teams, see the leaderboards.
		        	</div>
		        </div>
	        </section>
		</div>
        
        <!-- Fifth Step
        ==================================================-->
        <div class="span9 tab-pane" id="fifthStep" > 
	        <section >
		        <!-- <div class="page-header">
		        	<h1>5th Step</h1>
		        </div> -->
		        <div class="row">
		        	<div class="span5">
		        		<img class="sketch" src='<?php echo $this->baseUrl("images/sketch/yioupi.png"); ?>'>
		        	</div>
		        	<div class="span3 sketchText">
		        		Be local or global recycling leader and get the physical presents.
		        	</div>
		        </div>
	        </section>
		</div>
	</div>
    
</div>

<!-- End of Sticky Sidenav, and sketch content
    ==================================================-->

</div>