<div id="mainContent" class="row ">
	
	<div class="span7 offset1"  >
		<div class="well well-large " >
			<div class="media ">
				<span class="pull-left" >
				<img class="img-circle" src="http://placekitten.com/150/150">
				</span>
				<div class="media-body">
					<h2 class="media-heading">Media heading</h2>	
					<p>View script for controller <b>About</b> and script/action name <b>team</b> genika keimeno pl megalo me plirofories giat ta meloi tis omada  kai den eneimia kalsd</p>
				</div>
			</div>
		</div>
	</div>
	
	<div class="span7 offset1" >
		<div class="well well-large " >
			<div class="media ">
				<span class="pull-left" >
				<img class="img-polaroid-circle" src="http://placekitten.com/150/150">
				</span>
				<div class="media-body">
					<h2 class="media-heading">Media heading</h2>	
					<p>View script for controller <b>About</b> and script/action name <b>team</b> genika keimeno pl megalo me plirofories giat ta meloi tis omada  kai den eneimia kalsd</p>
				</div>
			</div>
		</div>
	</div>
	
	<div class="span7 offset1" >
		<div class="well well-large " >
			<div class="media ">
				<span class="pull-left" >
				<img class="img-polaroid" src="http://placekitten.com/150/150">
				</span>
				<div class="media-body">
					<h2 class="media-heading">Media heading</h2>	
					<p>View script for controller <b>About</b> and script/action name <b>team</b> genika keimeno pl megalo me plirofories giat ta meloi tis omada  kai den eneimia kalsd</p>
				</div>
			</div>
		</div>
	</div>
	
	<div class="span7 offset1" >
		<div class="well well-large " >
			<div class="media ">
				<span class="pull-left" >
				<img class="img-rounded" src="http://placekitten.com/150/150">
				</span>
				<div class="media-body">
					<h2 class="media-heading">Media heading</h2>	
					<p>View script for controller <b>About</b> and script/action name <b>team</b> genika keimeno pl megalo me plirofories giat ta meloi tis omada  kai den eneimia kalsd</p>
				</div>
			</div>
		</div>
	</div>
	
	<div class="span7 offset1" >
		<div class="well well-large " >
			<div class="media ">
				<span class="pull-left" >
				<img class="img-polaroid-rounded" src="http://placekitten.com/150/150">
				</span>
				<div class="media-body">
					<h2 class="media-heading">Media heading</h2>	
					<p>View script for controller <b>About</b> and script/action name <b>team</b> genika keimeno pl megalo me plirofories giat ta meloi tis omada  kai den eneimia kalsd</p>
				</div>
			</div>
		</div>
	</div>
	
	
	
</div>